//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Izdatelstvo
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IzdatelstvoEntities1 : DbContext
    {
        public IzdatelstvoEntities1()
            : base("name=IzdatelstvoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Manuscripts> Manuscripts { get; set; }
        public virtual DbSet<Sotrudniki> Sotrudniki { get; set; }
        public virtual DbSet<Writers> Writers { get; set; }


        private static IzdatelstvoEntities1 _context;
        public static IzdatelstvoEntities1 GetContext()
        {
            if (_context == null)
                _context = new IzdatelstvoEntities1();
            return _context;
        }
    }
}
